#!/bin/bash

CHIP=${CHIP:-24c128}
I2C_BUS=${I2C_BUS:-0}
I2C_ADDR=${I2C_ADDR:-50}

SYS=/sys/class/i2c-adapter/i2c-${I2C_BUS}
DEV=${SYS}/${I2C_BUS}-00${I2C_ADDR}


error()
{
    echo "*** ERROR: $*"
    exit 1
}

checkmod()
{
    lsmod | fgrep -q at24
}

checkdev()
{
    test -d ${DEV}
}

if [ -z "$1" ]
then
	error "No filename given"
fi

READ="$1"

if ! checkmod
then
	MLOAD=YES
	modprobe i2c_dev  || error "modprobe i2c_dev failed"
	modprobe at24 write_timeout=250  || error "modprobe at24 failed"
fi

if ! checkdev
then
	DLOAD=YES
        echo "${CHIP} 0x${I2C_ADDR}" > ${SYS}/new_device
fi

test -d ${SYS} || error "Directory ${SYS} does not exist"

dd of="${READ}" if=${DEV}/eeprom bs=1k status=none

if [ "${DLOAD}" == YES ]
then
        echo "0x${I2C_ADDR}" > ${SYS}/delete_device
fi

if [ "${MLOAD}" == YES ]
then
	rmmod at24
	rmmod i2c_dev
fi

