#!/bin/bash

ANCHORS='01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10'

for X in ${ANCHORS}
do
    ip -6 neigh replace fe80::72b3:d5b1:e000:01$X lladdr 70:b3:d5:b1:e0:00:01:$X dev lowpan0
done

#exec /sbin/utrack-anchor -s 10.100.1.125 -r 3.0
exec /sbin/utrack-anchor -r 3.0
