#!/bin/bash

N=$#
M=$((N-1))

DST=${@: $N:1}
ARG=${@: 1:$M}

HOST='bss'
LIST='1 2 3 4 5 6 7 8'

DOMAIN=${DOMAIN:-'.qs.unipart.io'}

IPVER=${IPVER:--4}


alive()
{
    ping ${IPVER} -c 3 -i 0.2 -W 1 -q "$@" 2>/dev/null >/dev/null
}

scopy()
{
    if alive ${1}
    then
	scp ${IPVER} ${ARG} root@${1}:${DST}
    else
    	echo "${1}: DEAD"
    fi
}


echo "Copying ${ARG} to ${DST}"

for X in ${LIST}
do
	scopy ${HOST}${X}${DOMAIN} &
done

wait

