#!/bin/bash

HOST='bss'
LIST='1 2 3 4 5 6 7 8'
EXEC='systemctl stop anchor ; systemctl status anchor | fgrep Active: | cut -c 12-'


alive()
{
    ping -c 3 -i 0.2 -W 1 -q "$@" 2>/dev/null >/dev/null
}

sexec()
{
    if alive ${HOST}${1}.qs.unipart.io
    then
    	echo "${HOST}${X}: $(ssh root@${HOST}${X}.qs.unipart.io ${EXEC})"
    else
    	echo "${HOST}${X}: DEAD"
    fi
}


for X in ${LIST}
do
    sexec ${X} &
done

wait

