#!/bin/bash

CHANNEL=${CHANNEL:-3}
PCODE=${PCODE:-12}
PRF=${PRF:-64}
RATE=${RATE:-850}
TXPSR=${TXPSR:-1024}
TXPWR=${TXPWR:-0x45454545}
SMART=${SMART:-0}
XTALT=${XTALT:-cal}
ANTD=${ANTD:-cal}

HOSTS='bss1 bss2 bss3 bss4 bss5 bss6 bss7 bss8'

bss-time
bss-start

cd ${HOME}/Projects/Tail/devel/rtls || exit 1

./dwattr.py -vv -s ${HOSTS} 		\
	    --channel ${CHANNEL} 	\
	    --pcode ${PCODE}		\
	    --prf ${PRF} 		\
	    --rate ${RATE} 		\
	    --txpsr ${TXPSR} 		\
	    --antd ${ANTD} 		\
	    --xtalt ${XTALT}		\
	    --smart_power ${SMART} 	\
	    --tx_power ${TXPWR} 	\
