#!/bin/bash

HOST='magpi'
LIST='0 1 2 3 4 5 6 7 8'
DOMAIN='.pinet'

FILE="$1"
EXEC='tar --extract --directory=/'


alive()
{ 
    ping -c 3 -i 0.2 -W 1 -q "$@" 2>/dev/null >/dev/null
}

timex()
{
    TIME="date -s \"$(date '+%Y/%m/%d %H:%M:%S')\""
    
    if alive ${1}${DOMAIN}
    then
	echo "${1}: $(ssh root@${1}${DOMAIN} ${TIME})"
    else
    	echo "${1}: DEAD"
    fi
}

sexec()
{
    if alive ${1}${DOMAIN}
    then
	echo "${1}: EXTRACT ${FILE}..."
	cat ${FILE} | ssh root@${1}${DOMAIN} "${EXEC}"
    else
    	echo "${1}: DEAD"
    fi
}


for X in ${LIST}
do
    timex ${HOST}${X} &
done

wait


for X in ${LIST}
do
    sexec ${HOST}${X} &
done

wait

