#!/bin/bash

NICE="nice -n10"

CHAINS="
${CHAIN}
/usr/local/tools/gcc-arm-8.2-2019.01-x86_64-arm-linux-gnueabihf
/usr/local/tools/gcc-arm-8.2-2018.11-x86_64-arm-linux-gnueabihf
/usr/local/tools/gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf
/usr/local/tools/gcc-linaro-arm-linux-gnueabihf-raspbian-x64
"

for DIR in ${CHAINS}
do
    if [ -d ${DIR} ]
    then
	export PATH="${DIR}/bin:${PATH}"
	echo "Using toolchain ${DIR##*/}"
	break
    fi
done

case $(uname -m) in
    armv7l)
	MAKE="make"
	;;

    x86_64)
	MAKE="make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-"
	;;
esac

exec ${NICE} ${MAKE} "$@"
