#!/bin/bash

PKGVERSION=${PKGVERSION:-0.0}
LOCALVERSION='+tail'

EMAIL='support@unipart'
FULLNAME='Unipart Digital'
HOMEPAGE='https://github.com/unipartdigital/linux-rpi'
DISTRIBUTION='raspbian'

CHAINS="${CHAIN}
gcc-arm-8.2-2019.01-x86_64-arm-linux-gnueabihf
gcc-linaro-arm-linux-gnueabihf-raspbian-x64
"

for DIR in ${CHAINS}
do
    if [ -d /usr/local/tools/${DIR} ]
    then
        export CHAIN=/usr/local/tools/${DIR}
        export PATH="${CHAIN}/bin:${PATH}"
	echo "Using toolchain ${DIR}"
	break
    fi
done

case $(uname -m) in
    armv7l)
	MAKE='make'
	;;
    
    x86_64)
	MAKE='make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-'
	;;
esac

exec ${MAKE} \
     LOCALVERSION="${LOCALVERSION}" \
     KDEB_PKGVERSION="${PKGVERSION}" \
     KDEB_CHANGELOG_DIST="${DISTRIBUTION}" \
     DEBEMAIL="${EMAIL}" \
     DEBFULLNAME="${FULLNAME}" \
     DEBHOMEPAGE="${HOMEPAGE}" \
     bindeb-pkg "$@"
