#!/bin/bash

EMAIL='support@unipart'
FULLNAME='Unipart Digital'
HOMEPAGE='https://github.com/unipartdigital/linux-rpi'
DISTRIBUTION='raspbian'
PKGVERSION=${PKGVERSION:-0.0}

MAKE=rpi-kernel-make

exec ${MAKE} \
     KDEB_PKGVERSION="${PKGVERSION}" \
     KDEB_CHANGELOG_DIST="${DISTRIBUTION}" \
     DEBEMAIL="${EMAIL}" \
     DEBFULLNAME="${FULLNAME}" \
     DEBHOMEPAGE="${HOMEPAGE}" \
     bindeb-pkg "$@"
