#!/bin/bash

LOCALVERSION=${LOCALVERSION:-+tail}

CHAINS="
${CHAIN}
gcc-arm-8.2-2019.01-x86_64-arm-linux-gnueabihf
gcc-linaro-arm-linux-gnueabihf-raspbian-x64
"

for DIR in ${CHAINS}
do
    if [ -d /usr/local/tools/${DIR} ]
    then
        export CHAIN=/usr/local/tools/${DIR}
        export PATH="${CHAIN}/bin:${PATH}"
	echo "Using toolchain ${DIR}"
	break
    fi
done

case $(uname -m) in
    armv7l)
	MAKE="make LOCALVERSION=${LOCALVERSION}"
	;;
    
    x86_64)
	MAKE="make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LOCALVERSION=${LOCALVERSION}"
	;;
esac

exec ${MAKE} "$@"
